#include <stdio.h>
#include <iostream>
#include <conio.h>
#include <iomanip>

using namespace std;

	// OPERASI LARIK
	/*
		LARIK ATAU ARRAY MENYATAKAN KUMPULAN DATA, DATA YANG TERKANDUNG DALAM SUATU LARIK
		HARUS BERTIPE SAMA

		LARIK DINYATAKAN DENGAN AWALAN HURUF KAPITAL DAN NOTASI [] DIPAKAI UNTUK MENYATAKAN
		DATA DALAM LARIK

		A = [1,2,3,4]
		MENYATAKAN LARIK A YANG BERISI DATA 1,2,3,4
		PADA CONTOH DIATAS LARIK A MEMILIKI 4 BUAH ELEMEN

		UNTUK MENYATAKAN SEBUAH ELEMEN DALAM LARIK NOTASINYA SEPERTI INI
		A[INDEKS]

		DALAM HAL INI INDEKS DIGUNAKAN UNTUK MENYATAKAN POSISI ELEMEN
		POSISI PERTAMA DIBERI KODE 0, POSISI KEDUA DIBERI ANGKA 1 DAN SETERUSNYA

		[1,2,3,4] INI ADALAH INDEKS

		PADA C++

		tipe_data nama_larik[jumlah_elemen]

		int cacah[4]; 	  LARIK cacah MEMPUNYAI 4 BUAH ELEMEN BERTIPE INT
		char vokal[5]; 	  LARIK vokal MEMPUNYAI 5 BUAH ELEMEN BERTIPE CHAR (CHARACTER)
		char kota[6][20]; LARIK kota MEMPUNYAI 6 BUAH ELEMEN BERTIPE STRING DENGAN
						  PANJANG MAKSIMAL SEBESAR 19 KARAKTER
		PENGAKSESAN ELEMEN LARIK DILAKUKAN DENGAN MENGGUNAKAN NOTASI

			nama_array[indeks]

			DALAM HAL INI INDEKS DIMULAI DARI 0
			CONTOH:
				   int cacah[4];
				   cacahh[0] = 1;
			MERUPAKAN PERNYATAAN UNTUK MENGISIKAN NILAI 1 KE ELEMEN PERTAMA PADA LARIK CACAH

			PADA SUATU LARIK BISA LANGSUNG DIISI DENGAN SUATU NILAI KETIKA LARIK TERSEBUT DIDEKLARASIKAN
			CONTOH:
				   int jum_hari[12]={31,28,31,30,31,30,31,31,30,31,30,31};

			PADA CONTOH DIATAS
				   jum_hari[0] bernilai 31
				   jum_hari[1] bernilai 28
				   jum_hari[2] bernilai 31
				   jum_hari[3] bernilai 30
				   DAN SETERUSNYA...

	*/

int main(){

	// CONTOH PROGRAM MENYIMPAN DATA HURUF VOKAL KEDALAM LARIK DAN MENAMPILKANNYA

	char kar[]={'A','B','C','D','E'};


	for(int i=0; i<=4; i++){

		cout << kar[i];
	}






	getch();
	return 0;
}
