#include <stdio.h>
#include <iostream>
#include <conio.h>

using namespace std;

	//INI ARTINYA AKAN MENDEFINISIKAN PI/NILAI PI JADI KETIKA DIPANGGIL DI DALAM MAIN MAKA PI NYA ITU AKAN DIGANTI SAJA
	#define PI 3.143248315

	//SEDANGKAN INI DIA MEMILIKI ADDRESS DAN DITARO DI DALAM MEMORY
	double pi = 3.143248315;

int main(){

	// SETIAP ADA TANDA # ITU ARTINYA PREPROCESSING DIRECTIVE
	// MAKA. ITU TIDAK ADA HUBUNGAN NYA DENGAN COMPILER/MEMORY
	// SETIAP KITA MENAMBAHKAN TANDA # MAKA DIA AKAN DISIMPAN KE PREPROCESSING

	//JADI SETIAP MEMANGGIL PI DIA KANA DIGANTI DENGAN NILAI NYA 3.143248315 ATAU ARTINYA KITA SAMA SAJA DENGA MENULIS 3.143248315
	cout << "Nilai dari PI: " << PI << endl;
	cout << "Nilai dari pi double: " << pi << endl;

	getch();
	return 0;
}
