
#include "bersama.h"
//JIKA FOO NYA ADA MAKA TIDAK AKAN MELAKUKAN APA-APA. JIKA TIDAK ADA MAKA AKAN MEMANGGGIL DI DALAM ELSE
//#ifdef FOO
//#else
//	#define FOO "INI ADALAH FOO DI DALAM BAR.H" //INI ELSE NYA
//#endif // FOO

//ATAU MEMAKAI IFNDEF
//KALAU SI FOO NYA TIDAK TERDEFINISI MAKA AKAN DEFINE FOO
//#ifndef FOO
//	#define FOO "INI ADALAH FOO DI DALAM BAR.H"
//#endif
