

/*INI MEMAKAI ARA IFNDEF
INI MEMBUAT GURT DIMULAI DENGAN TANDA _ . KALAU MACRO DIMULAI DENGAN HURUF KAPITAL
JIKA BERSAMA BELUM DI INCLUDE

#ifndef _BERSAMA
//MAKA KITA DEFINE SI BERSAMA NYA
#define _BERSAMA
struct mahasiswa{
	int NIM;
};

#endif
*/
//MEMAKAI CARA PRAGMA ONCE
//JADI SETIAP FILE BERSAMA.H DI ICNLUDE PASTIKAN TIDAK ADA DUPLIKAT NYA
#pragma once
struct mahasiswa{
	int NIM;
};

